version: "3.8"

services:
  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    container_name: nginx-rtmp
    restart: always
    ports:
      - "1935:1935"
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/logs/nginx
    networks:
      - streaming-net

  rtsp-server:
    image: bluenviron/mediamtx:latest-ffmpeg-rpi
    container_name: rtsp-server
    restart: always
    ports:
      - "8554:8554"      # RTSP
      - "9997:9997"      # Control
      - "9998:9998"      # Metrics
    volumes:
      - ${PWD}/rtsp-simple-server.yml:/mediamtx.yml:ro
      - ./logs/rtsp-server:/logs
    networks:
      - streaming-net

networks:
  streaming-net:
    driver: bridge